version: "3"
services:
  back:
    build: back/
    command: flask run --host 0.0.0.0
    ports:
      - "5000:5000"
    network_mode: host
  front:
    build: front/
    command: npx next dev
    ports:
      - "3000:3000"
    depends_on:
      - back